title: INE
baseline: Your blogging assistant
description: A ready to use static blog, powered by Cecil.
baseurl: /
canonicalurl: true
keywords: [Cecil, Static Site Generator, SSG]
author: Arnaud Ligny
date:
  format: j F Y
  timezone: Europe/Paris
theme:
  - hyde
  - netlify
  - netlify-cms
hyde:
  sidebar:
    sticky: true # Content to the bottom of the sidebar
  theme: '' # red, orange, yellow, green, cyan, blue, magenta, brown or cecil
  reverse: false # Reverse layout
