previewsEnabled: true
services:
- type: web
  name: Sabaila doministiku
  env: static
  buildCommand: curl -sSOL https://cecil.app/build.sh && bash ./build.sh
  staticPublishPath: _site
  pullRequestPreviewsEnabled: true
  headers:
  - path: /*
    name: X-Frame-Options
    value: DENY
  - path: /*
    name: X-XSS-Protection
    value: 1; mode=block
  - path: /*
    name: X-Content-Type-Options
    value: nosniff
  - path: /css/*
    name: Cache-Control
    value: public, max-age=31536000
  - path: /fonts/*
    name: Cache-Control
    value: public, max-age=31536000
  - path: /images/*
    name: Cache-Control
    value: public, max-age=31536000
  - path: /js/*
    name: Cache-Control
    value: public, max-age=31536000
